// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXShsCR_2g0BN-vAJTpeQYAeZbMxucGL8',
    appId: '1:419151776576:web:55b0fb5d5a76f05414c8a5',
    messagingSenderId: '419151776576',
    projectId: 'weatherly-96396',
    authDomain: 'weatherly-96396.firebaseapp.com',
    storageBucket: 'weatherly-96396.firebasestorage.app',
    measurementId: 'G-8M7R51FP93',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEtl_mN-JKNrXQKb4KQsyrhtFJ7WPY1Zc',
    appId: '1:419151776576:android:7b9eb5455f40cb1714c8a5',
    messagingSenderId: '419151776576',
    projectId: 'weatherly-96396',
    storageBucket: 'weatherly-96396.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0NrixBTzSmsbHBw6iKO8-AkGufldUAak',
    appId: '1:419151776576:ios:d62d7279804b1c1414c8a5',
    messagingSenderId: '419151776576',
    projectId: 'weatherly-96396',
    storageBucket: 'weatherly-96396.firebasestorage.app',
    iosBundleId: 'com.example.weatherapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0NrixBTzSmsbHBw6iKO8-AkGufldUAak',
    appId: '1:419151776576:ios:d62d7279804b1c1414c8a5',
    messagingSenderId: '419151776576',
    projectId: 'weatherly-96396',
    storageBucket: 'weatherly-96396.firebasestorage.app',
    iosBundleId: 'com.example.weatherapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXShsCR_2g0BN-vAJTpeQYAeZbMxucGL8',
    appId: '1:419151776576:web:547f6bc44236c1fd14c8a5',
    messagingSenderId: '419151776576',
    projectId: 'weatherly-96396',
    authDomain: 'weatherly-96396.firebaseapp.com',
    storageBucket: 'weatherly-96396.firebasestorage.app',
    measurementId: 'G-ND955MG621',
  );
}
